EMPRESAS ADM: Funcionario Class Reference
Funcionario Class Reference
#include "funcionario.h"
Public Member Functions
Funcionario ()
Funcionario (string nome, double salario, Data dataAdmissao)
~Funcionario ()
string getNome ()
void setNome (string nome)
double getSalario ()
void setSalario (double salario)
Data getDataAdmissao ()
void setDataAdmissao (Data dataAdmissao)
string getNomeEmpresa ()
void setNomeEmpresa (string nomeEmpresa)
Funcionario & operator= (Funcionario const &f)
Private Attributes
string nome
double salario
Data dataAdmissao
string nomeEmpresa
Friends
ostream & operator<< (ostream &o, Funcionario const f)
Detailed Description
Definition at line 17 of file funcionario.h.
Constructor & Destructor Documentation
Funcionario() [1/2]
Funcionario::Funcionario ()
Definition at line 2 of file funcionario.cpp.
{
 }
Funcionario() [2/2]
Funcionario::Funcionario (string nome, double salario, Data dataAdmissao)
Definition at line 5 of file funcionario.cpp.
References dataAdmissao, nome, and salario.
{
     this->nome = nome;
     this->salario = salario;
     this->dataAdmissao = dataAdmissao;
 }
~Funcionario()
Funcionario::~Funcionario ()
Definition at line 23 of file funcionario.cpp.
 {};
Member Function Documentation
getDataAdmissao()
Data Funcionario::getDataAdmissao () inline
Definition at line 39 of file funcionario.h.
Referenced by checarExperiencia().
{
             return this->dataAdmissao;
         };
getNome()
string Funcionario::getNome () inline
Definition at line 27 of file funcionario.h.
Referenced by checarFuncionario().
{
             return this->nome;
         };
getNomeEmpresa()
string Funcionario::getNomeEmpresa () inline
Definition at line 45 of file funcionario.h.
Referenced by iniciarMenu().
{
             return this->nomeEmpresa;
         }
getSalario()
double Funcionario::getSalario () inline
Definition at line 33 of file funcionario.h.
{
             return this->salario;
         };
operator=()
Funcionario & Funcionario::operator= (Funcionario const & f)
Definition at line 11 of file funcionario.cpp.
References dataAdmissao, nome, and salario.
{
     this->nome =f.nome;
     this->salario = f.salario;
     this->dataAdmissao = f.dataAdmissao;
     return *this;
 }
setDataAdmissao()
void Funcionario::setDataAdmissao (Data dataAdmissao) inline
Definition at line 42 of file funcionario.h.
{
             this->dataAdmissao = dataAdmissao;
         };
setNome()
void Funcionario::setNome (string nome) inline
Definition at line 30 of file funcionario.h.
{
             this->nome = nome;
         };
setNomeEmpresa()
void Funcionario::setNomeEmpresa (string nomeEmpresa) inline
Definition at line 48 of file funcionario.h.
References operator<<().
Referenced by adicionarFuncionario().
{
             this->nomeEmpresa = nomeEmpresa;
         }
setSalario()
void Funcionario::setSalario (double salario) inline
Definition at line 36 of file funcionario.h.
{
             this->salario = salario;
         };
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & o, Funcionario const f) friend
Definition at line 18 of file funcionario.cpp.
{
     o << "nome: " << f.nome << " | salario : " << f.salario << " | contratado em: "<< dateToString(f.dataAdmissao) << " por " << f.nomeEmpresa << endl;
     return o;
 }
Member Data Documentation
dataAdmissao
Data Funcionario::dataAdmissao private
Definition at line 21 of file funcionario.h.
Referenced by Funcionario(), operator<<(), and operator=().
nome
string Funcionario::nome private
Definition at line 19 of file funcionario.h.
Referenced by Funcionario(), operator<<(), and operator=().
nomeEmpresa
string Funcionario::nomeEmpresa private
Definition at line 22 of file funcionario.h.
Referenced by operator<<().
salario
double Funcionario::salario private
Definition at line 20 of file funcionario.h.
Referenced by Funcionario(), operator<<(), and operator=().
The documentation for this class was generated from the following files:
funcionario.h
funcionario.cpp